### ISSUE TITLE
Improve speed of cuts.isQSO_randomforest.predict_proba

### ISSUE THREAD

**Issue by sbailey** [desihub/desitarget#404] opened 2018-10-16 12:32 UTC
From PR #403: `cuts.isQSO_randomforest.predict_proba` is very slow.  @moustakas found that it took ~19 seconds to process ~150 candidates, which is a blocking factor for effectively creating mocks.  Profile this and figure out why it is so slow and fix it.  If it can't be accomplished with more effective numpy vector logic, this could be a candidate for using `@numba.jit`.

Assigning to @geordie666 and mentioning @moustakas and @forero to keep them in the loop.

**Comment by lastephey** [comment] 2018-10-16 15:17
Sorry to bust into your thread but just went live with some new python
profiling documentation that might be helpful for you:

https://docs.nersc.gov/development/high-level-environments/python/profiling-python/

It's still somewhat rough so if you find problems or have things you'd like
to see changed please let me know.

**Comment by geordie666** [comment] 2018-10-16 19:35
I agree with @moustakas that the quasar random forest code is slow for 150 objects, e.g.:

```
N = 150
from desitarget.cuts import _prepare_optical_wise, _get_colnames, isQSO_randomforest
from time import time
from desitarget import io
fn = "/global/project/projectdirs/cosmo/data/legacysurvey/dr7/sweep/7.1/sweep-120p015-130p020.fits"
objects = io.read_tractor(fn)
objects = objects[:N]
colnames = _get_colnames(objects)
photsys_north, photsys_south, obs_rflux, gflux, rflux, zflux,              \
  w1flux, w2flux, objtype, release, gfluxivar, rfluxivar, zfluxivar,     \
  gnobs, rnobs, znobs, gfracflux, rfracflux, zfracflux,                  \
  gfracmasked, rfracmasked, zfracmasked,                                 \
  gfracin, rfracin, zfracin, gallmask, rallmask, zallmask,               \
  gsnr, rsnr, zsnr, w1snr, w2snr, dchisq, deltaChi2, brightstarinblob =  \
                             _prepare_optical_wise(objects, colnames=colnames)
t0 = time()
dum = isQSO_randomforest(primary=None, zflux=zflux, rflux=rflux, gflux=gflux,
  w1flux=w1flux, w2flux=w2flux, deltaChi2=deltaChi2,
  objtype=objtype, release=release, south=False)
print("{} objects processed in t = {}s".format(len(objects),time()-t0))
    ...:  
150 objects processed in t = 14.500774383544922s
```
On the other hand, the same code for `N=1000000` returns:
```
1000000 objects processed in t = 31.1025550365448s
```
So, it's not really limiting in the case of the real data when we tend to pass a few million objects parallelized over a few 100 processes. In other words, the simplest solution is not to pass the code only 150 objects!

I haven't run @lastephey's full profiler, but I suspect that there's some initialization or I/O step in `isQSO_randomforest` that can be moved out of the sub-functions and instantiated only once. I'll dig into that.

**Comment by geordie666** [comment] 2018-10-16 21:12
Actually, this isn't really due to an initialization step being repeatedly called. Initialization is quick. The issue is that the code recursively traverses the tree(s) in `searchNodes` to some convergence limit.

https://github.com/desihub/desitarget/blob/master/py/desitarget/myRF.py#L42-L76

The code operates on an array of input data, so, it doesn't matter (much) if your input array size is `N=150` or `N=1000000`, you'll recursively traverse roughly the same number of levels down the tree(s) to find solutions for the `N=150` or `N=1000000` entries in the data array. The code in the recursion seems quite optimal, it's just (relatively) inefficient to use a recursive tree structure for small amounts of data.

I'm looping in @Cyeche who provided the original version of the code. I'm hoping he can think of some way to speed it up.

**Comment by moustakas** [comment] 2018-10-16 23:40
Unfortunately `select_mock_targets` is parallelized over ~smallish healpixels because otherwise it runs into memory issues (it has to hold target catalogs, truth catalogs, *and* spectra for all the target classes in memory), and so for target classes like QSOs it passes no more than a few hundred targets at a time to target selection.

Since speed isn't a blocking factor for running target selection on "real" catalogs, and given the level of (in)accuracy of the mock photometric catalogs, I don't think we need to spend much time on this. I think that QSO color-cuts should be more than sufficient for generating mock target catalogs.

**Comment by geordie666** [comment] 2018-10-16 23:42
@moustakas: I agree. Shall we close this issue?

**Closed** 2018-10-16 23:43 UTC
Labels: enhancement
