### ISSUE TITLE
MTL should flag when NOBS and/or PRIORITY changed and why

### ISSUE THREAD

**Issue by moustakas** [desihub/desitarget#343] opened 2018-08-10 17:49 UTC
From the discussion on a recent Data telecon (see [desi-data 3720](https://desi.lbl.gov/trac/tracmailman/browser/private/desi-data/2018-August/003723.html) for details):

MTL should have a way to flag when it has changed the original NOBS or PRIORITY to something else and why.

Quoting from the minutes, here are some additional details:
> Discussed but didn't converge about whether the original NOBS (number of desired observations) and PRIORITY should be treated as a fundamental output in the original target selection catalog or whether they only belong in the dynamic MTL (merged target list) because they change with time based upon observing history.  i.e. the original NOBS and PRIORITY are just what the values are in the first MTL; is there value in having them in the original catalog too?  There was disagreement about whether this is valuable or prone to mis-interpretation.

**Comment by geordie666** [comment] 2018-08-10 18:03
Context:

This flag should be a static bitmask that lists the categories apropos why changes could occur. 

This might be complicated if we have the possibility that things could change multiple times for the same reason (say, a change, and then a change back again, and then the original change) which I don't *think* can happen. Multiple such changes could be recorded by appending the bitmask value to an array every time MTL updated, if needed.

**Comment by sbailey** [comment] 2018-08-13 22:46
More context.  Currently the PRIORITY changes based upon observing and processing state defined in [targetmask.yaml](https://github.com/desihub/desitarget/blob/master/py/desitarget/data/targetmask.yaml).  For targets that are finished, they get both NOBS_MORE=0 and PRIORITY=(something small, configured by that yaml file) such that every target that gets observed has its priority change.  We could consider leaving the PRIORITY alone and just changing NOBS_MORE in that case, such that PRIORITY doesn't change if everything was fine.

Currently each bit can get a different priority for each of these states:
* UNOBS: not yet observed
* OBS: observed but not yet processed (currently unimplemented because the way we call fiberassign doesn't know that it has been observed it if hasn't been processed...)
* MORE_ZGOOD: good redshift but we want more observations (e.g. LyA QSO)
* MORE_ZWARN: ambiguous redshift but we want more observations
* DONE: have achieved the originally requested number of observations
* DONOTOBSERVE: placeholder for flagging objects not to observe again.

If a target passes more than one set of cuts, the highest priority one wins for setting the priority.

**Comment by geordie666** [comment] 2018-08-13 22:51
I've been looking at this a little bit, too...what do you think of the idea of just expanding this mask? We could have, for instance:

- NOT_QSO: Stopped observing this object because it was deemed that it wasn't a quasar
etc.

We'd have to come up with an exhaustive set of reasons that `NOBS_MORE` could change, but it should be transparent if we understand that full set.

**Comment by kdawson1000** [comment] 2018-08-13 23:51
All of this sounds good to me.  I really think we should not change PRIORITY and implement the suggestions of Adam and Stephen on the NOBS_MORE and associated mask.  I imagine that the mask will continue to expand as we realize we need more issues to track.  e.g. broken fiber;  Corrupted sky target;   Corrupted std star target;  bits for MWS?  bits for secondary targets?

**Comment by sbailey** [comment] 2018-08-14 00:49
@geordie666 if by "this mask" you mean a new mask of reasons why NOBS or PRIORITY changes, then ok.  But to be clear: we shouldn't be updating bits in DESI_TARGET post-facto (it is sacrosanct unchanging protected by the highest level of magic spells).

@kdawson1000 we could minimize the number of cases where PRIORITY might change (e.g. when changing NOBS_MORE would be equivalent), but there will be reasonable cases where we would want to change PRIORITY based on initial observations, e.g. prioritizing finishing a confirmed LyA QSO instead of getting a new observation of a different unobserved QSO target.

**Comment by geordie666** [comment] 2020-08-12 21:09
This is addressed in #635, as the MTL ledger includes a `TARGET_STATE` column that looks like: 

`MERGED_TARGET_TYPE |OBSERVATIONAL_STATE`
e.g.
`QSO|MORE_ZGOOD`
or
`LRG|DONE`

I'll leave this open for now, though, until we've decided to what degree we will implement #635 downstream.

**Closed** 2021-07-20 17:56 UTC
